ALTER TABLE questions DROP CONSTRAINT IF EXISTS questions_category_check;
ALTER TABLE questions ADD CONSTRAINT questions_category_check CHECK (category IN ('habits','food','work','relationships','social','sleep','money','spicy'));

insert into questions (text, option_a, option_b, category) values
('Have you ever reworn clothes without washing them?','Guilty 😈','Never 😇','habits'),
('Have you ever eaten food you dropped on the floor?','Obviously','Absolutely not','habits'),
('Do you talk to yourself out loud when alone?','Constantly','Not me','habits'),
('Have you ever doomscrolled for more than an hour without realizing it?','Every single day','Who does that?','habits'),
('Do you have a procrastination ritual before you start anything?','I''ve perfected mine','I just start','habits'),
('Do you secretly follow superstitions you''d be embarrassed to admit?','More than one','Not superstitious','habits'),
('Have you ever skipped showering for 2+ days when you had nowhere to be?','Yes and I''d do it again','Never happened','habits'),
('Have you ever sniffed clothes to decide if they''re clean enough?','Every single time','Who does that?','habits'),
('Do you pick at your skin or cuticles when anxious?','Constantly','Not me','habits'),
('Have you ever eaten snacks straight from the box?','Obviously','Absolutely not','habits'),
('Do you leave messages on read until it''s embarrassingly late?','Every time','I reply straight away','habits'),
('Have you ever faked being on your phone to avoid a conversation?','More than once','I would never','habits'),
('Do you pee in the shower?','No comment 👀','Hard no','habits'),
('Have you ever reused a disposable cup or plate multiple times?','Guilty 😈','Never 😇','habits'),
('Do you leave empty containers in the fridge for someone else to deal with?','Every single time','I always deal with it','habits'),
('Have you ever tidied by shoving everything into a closet?','That''s just cleaning','I tidy properly','habits'),
('Do you wash your bedsheets less than once a month?','No comment 👀','Clean conscience','habits'),
('Have you ever worn clothing inside out and just left it?','Caught in 4K 😭','Never done that','habits'),
('Do you have an embarrassing alter-ego voice you use when alone?','They have a name','Definitely not','habits'),
('Have you ever convinced yourself you were seriously ill after googling symptoms?','I''m probably dying','I don''t self-diagnose','habits'),
('Do you set alarms knowing you''ll snooze at least 3 times?','That''s the system','One alarm, I''m up','habits'),
('Have you ever stayed in a bad mood on purpose because it felt easier?','More than I''d admit','Never','habits'),
('Do you narrate your own life in your head like a documentary?','In full voiceover','Not even close','habits'),
('Have you ever eaten something from your bag you couldn''t remember buying?','Obviously','That''s odd, no','habits'),
('Do you have a ritual for entering or leaving a room that nobody knows about?','They''d think I''m unwell','Nothing like that','habits'),
('Have you ever kept using something broken rather than getting it fixed?','For years','I fix things promptly','habits'),
('Do you refresh your notifications the second you post something?','Every few seconds','I forget I posted','habits'),
('Have you ever pretended to be asleep to avoid a conversation?','More than once','I would never','habits'),
('Do you rehearse arguments in the shower that will never happen?','And I always win','Never','habits'),
('Have you ever worn pajamas all day without originally intending to?','That''s called a weekend','I always get dressed','habits');

insert into questions (text, option_a, option_b, category) values
('Do you talk to your pets like they understand full sentences?','In multiple languages','They''re just animals','habits'),
('Have you ever lied about having read a book you haven''t opened?','More than once','I would never','habits'),
('Do you smell new things before using them?','Always','That''s strange, no','habits'),
('Have you ever eaten food from someone''s plate they left unattended?','It was going to waste','Never','habits'),
('Do you pick your nose when you''re completely alone?','Obviously','Absolutely not','habits'),
('Have you ever fake-laughed at something unfunny just to seem normal?','Constantly','I keep it honest','habits'),
('Do you give running commentary while cooking alone?','Full cooking show energy','I cook in silence','habits'),
('Have you ever worn the same socks 2+ days in a row?','Guilty 😈','Never 😇','habits'),
('Do you delay app updates until your phone practically begs you?','Every single app','I update immediately','habits'),
('Have you ever drunk something straight from the carton?','Yes and I''d do it again','Never happened','habits'),
('Do you keep things you never use just in case you might need them someday?','My home proves it','I declutter regularly','habits'),
('Have you ever apologized for something you weren''t remotely sorry for?','Constantly','I only apologize genuinely','habits'),
('Do you name inanimate objects like your car or plants?','They''re family','That''s a bit much','habits'),
('Have you ever promised to start something on Monday and then not done it?','Every single Monday','I start when I say','habits'),
('Do you chew on pens, pencils, or your phone case?','Constantly','Never','habits'),
('Have you ever sung in public thinking no one could hear you?','Caught in 4K 😭','I don''t do that','habits'),
('Do you make specific sounds or gestures when alone that you''d never do publicly?','Between me and the walls','Nothing like that','habits'),
('Have you ever avoided doing laundry by just buying new underwear?','Guilty 😈','Never 😇','habits'),
('Do you leave lights on in rooms you''ve already left?','Every room','I always switch them off','habits'),
('Have you ever had a phase of googling deeply embarrassing niche content?','No comment 👀','I have normal searches','habits'),
('Do you have a comfort food ritual you''d be too embarrassed to describe?','It''s mine only','Nothing embarrassing','habits'),
('Have you ever immediately needed another snack right after finishing one?','The cycle never ends','I have self-control','habits'),
('Do you sit in a position alone that would look ridiculous to others?','Fully folded somehow','I sit normally','habits'),
('Have you ever shoved things out of sight right before guests arrived?','That IS tidying','I tidy properly','habits'),
('Do you check your phone every few minutes for no specific reason?','Every single minute','I use it intentionally','habits'),
('Have you ever said you''d do something in 5 minutes, over 10 times in one day?','The 5 minutes never came','I do things when I say','habits'),
('Do you have a specific walk or dance you only do when you''re alone?','I have full choreography','I move normally','habits'),
('Have you ever counted calories and then immediately eaten more out of spite?','Every time I try','That hasn''t happened','habits'),
('Do you have a secret playlist you''d be embarrassed for anyone else to hear?','Deeply shameful content','My taste is fine','habits'),
('Have you ever spent 30+ minutes choosing what to watch and then watched nothing?','Then closed the app','I decide quickly','habits');

insert into questions (text, option_a, option_b, category) values
('Have you ever eaten cold leftovers straight from the container at midnight?','Obviously','Absolutely not','food'),
('Do you have a food combination other people find genuinely disgusting?','It slaps though','Never','food'),
('Have you ever eaten someone else''s food without asking?','It was going to waste','I would never','food'),
('Do you eat the same meal on repeat for days without getting bored?','Constantly','Not me','food'),
('Have you ever lied about dietary restrictions to avoid a food you dislike?','Guilty 😈','Never 😇','food'),
('Do you eat in secret when no one''s watching?','More than I''d admit','Never','food'),
('Have you ever eaten dessert before your main meal?','Obviously','Absolutely not','food'),
('Do you scrape the plate or bowl completely clean every single time?','Every single time','Who does that?','food'),
('Have you ever eaten an entire sharing bag of crisps or chips by yourself?','Yes and I''d do it again','Never happened','food'),
('Do you silently judge people who leave food on their plate?','Constantly','Not me','food'),
('Have you ever eaten a flatmate''s or roommate''s food without permission?','Guilty 😈','Never 😇','food'),
('Do you eat straight from the pan to avoid doing dishes?','Obviously','Absolutely not','food'),
('Have you ever eaten food that was clearly past its use-by date?','More than once','I would never','food'),
('Do you put bizarre things on toast that nobody else would?','It works, trust me','Never','food'),
('Have you ever tasted something at a supermarket before deciding to buy it?','Obviously','Absolutely not','food'),
('Have you ever ordered the exact same takeaway item more than 10 times?','It''s my go-to','Never that consistently','food'),
('Do you hide snacks so you don''t have to share them?','Constantly','Not me','food'),
('Have you ever eaten a whole jar of Nutella or peanut butter straight from the jar?','Caught in 4K 😭','Clean conscience','food'),
('Do you pretend to be full specifically to protect your dessert?','Guilty 😈','Never 😇','food'),
('Have you ever eaten food off someone''s plate without being offered it?','If it was there...','I would never','food'),
('Do you have an embarrassingly childish food preference — plain pasta, no sauce?','Plain and proud','Not remotely','food'),
('Have you ever made a meal so lazy it barely counted as food?','Crackers and regret','I cook properly','food'),
('Do you eat while standing over the sink?','Obviously','Absolutely not','food'),
('Have you ever used a piece of food as a utensil to avoid washing a spoon?','Every time','Never','food'),
('Have you ever stress-eaten an entire packet of biscuits or cookies in one sitting?','More than once','I would never','food'),
('Do you reach for snacks over a proper meal when you''re tired?','Every single time','Who does that?','food'),
('Have you ever re-plated delivered food to pretend you cooked it?','Yes and I''d do it again','Never happened','food'),
('Do you always order the same thing at restaurants you visit regularly?','Constantly','Not me','food'),
('Have you ever gone for seconds before everyone else had firsts?','Guilty 😈','Never 😇','food'),
('Do you eat food that''s fallen on the table — not the floor, just the table?','Obviously','Absolutely not','food');

insert into questions (text, option_a, option_b, category) values
('Have you ever eaten so much in one go you had to lie flat afterward?','More than once','I would never','food'),
('Do you skip breakfast and convince yourself it''s completely fine?','Every day','I always eat breakfast','food'),
('Have you ever drunk the milk straight from the cereal bowl?','Obviously','Never','food'),
('Have you ever eaten an entire loaf of bread across one single day?','Caught in 4K 😭','Clean conscience','food'),
('Do you dip things in things they weren''t designed for — crisps in ice cream, chips in milkshake?','It enhances everything','Absolutely not','food'),
('Have you ever eaten a full meal standing in the kitchen while insisting you were just tasting?','That was dinner','I eat at the table','food'),
('Do you silently judge people who don''t share your taste in food?','Constantly','Not me','food'),
('Have you ever eaten so fast you had no memory of actually tasting it?','Every stressful meal','Never','food'),
('Do you eat the best topping off first before the rest?','Every time','I eat it as designed','food'),
('Have you ever hoarded snacks on a flight or long journey?','Obviously','Absolutely not','food'),
('Do you have a go-to emotional eating food that has seen you through some things?','More than one','I process emotions differently','food'),
('Have you ever faked being on a diet to avoid food at a social event?','More than once','I would never','food'),
('Do you eat the bread crusts most people skip?','Every single one','Never','food'),
('Have you ever made a full meal entirely from condiments and random fridge items?','Caught in 4K 😭','Clean conscience','food'),
('Do you eat cereal as a legitimate meal at any time of day?','Obviously','Absolutely not','food'),
('Have you ever scraped the mould off food and eaten the rest?','No comment 👀','Hard no','food'),
('Do you take food from shared plates before everyone has been served?','Guilty 😈','Never 😇','food'),
('Have you ever pretended you weren''t hungry to seem polite, then eaten alone later?','More than once','I would never','food'),
('Do you tell yourself just one and then finish the entire thing every time?','Every single time','Who does that?','food'),
('Have you ever eaten fast food more than 3 times in a single week?','Yes and I''d do it again','Never happened','food'),
('Do you pour extra sauce or dressing without asking or telling anyone?','Constantly','Not me','food'),
('Have you ever thrown away gifted food you knew you''d never eat?','Quietly, yes','I would never','food'),
('Do you have a food you pretend to like publicly but genuinely dislike?','More than one','Nothing like that','food'),
('Have you ever convinced yourself a snack doesn''t count because it came from someone else''s bag?','Not my calories','I count everything','food'),
('Do you eat free samples at stores with zero intention of buying?','Every single one','I only try what I might buy','food'),
('Have you ever eaten the same leftovers 4+ days in a row?','Obviously','Never','food'),
('Do you season your food before tasting it?','Obviously','Absolutely not','food'),
('Have you ever microwaved midnight food trying not to make a sound?','Caught in 4K 😭','Clean conscience','food'),
('Do you eat different items on your plate in a specific order every time?','The system is sacred','I eat randomly','food'),
('Have you ever found forgotten food in a bag and seriously considered eating it?','More than once','I would never','food');

insert into questions (text, option_a, option_b, category) values
('Have you ever called in sick when you were perfectly fine?','Obviously','Absolutely not','work'),
('Do you do the bare minimum at work and feel completely fine about it?','Constantly','Not me','work'),
('Have you ever been paid for a full day of doing almost nothing?','More times than I''d admit','Never','work'),
('Do you talk negatively about your company to people outside it?','Guilty 😈','Never 😇','work'),
('Have you ever taken credit for a colleague''s idea or work?','No comment 👀','Hard no','work'),
('Do you have a fake-busy technique you use when you need to look productive?','I''ve perfected it','Never needed one','work'),
('Have you ever seen a work message and deliberately not responded?','More than once','I would never','work'),
('Do you stay at your job purely for the money despite disliking it?','Every day, sadly','I love my job','work'),
('Have you ever been visibly caught doing nothing at work?','Caught in 4K 😭','Clean conscience','work'),
('Do you spend more than an hour on personal things during work hours?','Obviously','Absolutely not','work'),
('Have you ever lied about the reason you were late?','More than once','I would never','work'),
('Do you think most of your meetings could have been an email?','Every single one','Meetings have value','work'),
('Have you ever fallen asleep during a work meeting?','Guilty 😈','Never 😇','work'),
('Do you avoid a specific colleague because they create more work for you?','Constantly','Not me','work'),
('Have you ever let someone else take the blame for your mistake?','No comment 👀','Hard no','work'),
('Do you only pretend to care about team-building activities?','Obviously','Absolutely not','work'),
('Have you ever applied for jobs while telling everyone you love your current role?','Yes and I''d do it again','Never happened','work'),
('Do you think you''re underpaid compared to at least one colleague?','Obviously','Absolutely not','work'),
('Have you ever exaggerated something on a performance review?','Guilty 😈','Never 😇','work'),
('Do you use flexible working as an opportunity to do noticeably less?','More than I should','Never','work'),
('Have you ever spent 2+ hours on YouTube or social media during a workday?','More than once','I would never','work'),
('Do you have a noticeably different personality at work compared to real life?','Completely different person','I''m always myself','work'),
('Have you ever forwarded a private work message to someone outside the company?','No comment 👀','Hard no','work'),
('Do you avoid taking on new responsibilities specifically to stay comfortable?','Constantly','Not me','work'),
('Have you ever taken office supplies home for personal use?','Obviously','Absolutely not','work'),
('Do you regularly talk about colleagues behind their back?','Caught in 4K 😭','Clean conscience','work'),
('Have you ever interviewed somewhere purely to get a competing offer for a raise?','More than once','I would never','work'),
('Do you feel genuine guilt about how little you actually do at work?','Every single day','Never','work'),
('Have you ever ghosted a recruiter after accepting a different offer?','Guilty 😈','Never 😇','work'),
('Do you think imposter syndrome quietly drives most of your career decisions?','Constantly','Not me','work');

insert into questions (text, option_a, option_b, category) values
('Have you ever attended a work event specifically and only for the free food?','Obviously','I go for the content','work'),
('Do you mentally check out during meetings and nod along on autopilot?','Every single one','I''m fully present','work'),
('Have you ever stretched your qualifications in a job interview?','More than once','I would never','work'),
('Do you secretly believe you could do your manager''s job better than they do?','Obviously','Absolutely not','work'),
('Have you ever adjusted a deadline without telling anyone to manage your own workload?','Caught in 4K 😭','Clean conscience','work'),
('Do you avoid giving honest feedback to avoid any confrontation?','Constantly','Not me','work'),
('Have you ever taken a very long bathroom break just to escape your desk?','More than once','I would never','work'),
('Do you only work harder when you know someone is watching?','Guilty 😈','Never 😇','work'),
('Have you ever taken a sick day that was really a hangover or mental health day?','Yes and I''d do it again','Never happened','work'),
('Do you start clock-watching from around 2pm every single workday?','Obviously','Absolutely not','work'),
('Have you ever significantly reused someone else''s work and submitted it as your own?','No comment 👀','Hard no','work'),
('Do you decline calls you could easily just pick up?','Constantly','Not me','work'),
('Have you ever joined a video call and done something completely unrelated the whole time?','More than once','I would never','work'),
('Do you put minimal effort into things you know nobody reviews properly?','Obviously','Absolutely not','work'),
('Have you ever been dismissive to a colleague and acted like nothing happened?','Caught in 4K 😭','Clean conscience','work'),
('Do you use working from home as an opportunity to do noticeably less?','Guilty 😈','Never 😇','work'),
('Have you ever billed a completely unproductive day as a full day of work?','More than once','I would never','work'),
('Do you set deadlines you have no real intention of meeting?','Constantly','Not me','work'),
('Have you ever accidentally sent an email that was clearly meant for someone else?','Obviously','Absolutely not','work'),
('Do you quietly resent colleagues who are more visibly successful?','No comment 👀','Hard no','work'),
('Have you ever blamed a technical issue to buy yourself more time on a deadline?','Yes and I''d do it again','Never happened','work'),
('Do you actively avoid the hardest parts of your job when possible?','Constantly','Not me','work'),
('Have you ever been promoted and immediately thought it was a mistake?','More than once','I would never','work'),
('Do you only work hard when there''s a clear reward or consequence attached?','Guilty 😈','Never 😇','work'),
('Have you ever taken 45+ minutes for lunch without logging it?','Obviously','Absolutely not','work'),
('Do you make jokes about your company or job publicly online?','Caught in 4K 😭','Clean conscience','work'),
('Have you ever submitted work you knew wasn''t good enough just to clear it off your plate?','More than once','I would never','work'),
('Do you genuinely feel like a fraud in your current role?','Constantly','Not me','work'),
('Have you ever been so bored at work you seriously considered quitting on the spot?','Yes and I''d do it again','Never happened','work'),
('Do you count down to your next holiday from essentially your first day back?','Every single time','I live in the present','work');

insert into questions (text, option_a, option_b, category) values
('Have you ever checked a partner''s phone without them knowing?','No comment 👀','Hard no','relationships'),
('Do you compare your current partner to people from your past?','Constantly','Not me','relationships'),
('Have you ever stayed in a relationship for convenience rather than love?','More than once','I would never','relationships'),
('Is there an ex you''d go back to if they asked you right now?','Guilty 😈','Never 😇','relationships'),
('Have you ever obsessively scrolled someone''s social media without them knowing?','Obviously','Absolutely not','relationships'),
('Do you bring up old arguments or incidents during new ones?','Every single time','Who does that?','relationships'),
('Have you ever lied to a partner about where you were or who you were with?','More than once','I would never','relationships'),
('Do you stay connected to exes out of jealousy more than genuine care?','No comment 👀','Hard no','relationships'),
('Have you ever given someone the silent treatment for more than 2 days?','Yes and I''d do it again','Never happened','relationships'),
('Do you test a partner''s loyalty without telling them you''re doing it?','Guilty 😈','Never 😇','relationships'),
('Have you ever felt secretly relieved when a relationship ended, even if you cried?','Caught in 4K 😭','Clean conscience','relationships'),
('Do you tend to be attracted to people who aren''t good for you?','Constantly','Not me','relationships'),
('Have you ever stayed in a relationship mainly to avoid being alone?','More than once','I would never','relationships'),
('Do you compare your relationship to others based on what you see on social media?','Obviously','Absolutely not','relationships'),
('Have you ever said I love you without fully meaning it?','No comment 👀','Hard no','relationships'),
('Do you hold grudges long after you''ve outwardly forgiven someone?','Every single time','Who does that?','relationships'),
('Have you ever hidden how you really felt just to keep the peace?','More than once','I would never','relationships'),
('Do you replay arguments in your head for days afterward?','Constantly','Not me','relationships'),
('Have you ever looked through a partner''s search history?','Guilty 😈','Never 😇','relationships'),
('Do you say I''m fine when you are clearly not fine?','Obviously','Absolutely not','relationships'),
('Have you ever used intimacy as a reward or withheld it as a punishment?','No comment 👀','Hard no','relationships'),
('Do you secretly judge your partner''s choices while pretending to be supportive?','More than once','I would never','relationships'),
('Have you ever emotionally checked out of a relationship well before officially ending it?','Yes and I''d do it again','Never happened','relationships'),
('Do you overshare relationship problems with people outside the relationship?','Caught in 4K 😭','Clean conscience','relationships'),
('Have you ever had a period of falling out of love with someone and then back in?','More than once','Never happened','relationships'),
('Do you keep a just-in-case contact — someone you''d consider going back to?','Obviously','Absolutely not','relationships'),
('Have you ever tried to make someone jealous on purpose?','Guilty 😈','Never 😇','relationships'),
('Do you feel smothered easily when a relationship gets close?','Constantly','Not me','relationships'),
('Have you ever lied to a partner about how many people you''ve been with?','No comment 👀','Hard no','relationships'),
('Do you pull away when a relationship starts getting too serious?','Every single time','Who does that?','relationships');

insert into questions (text, option_a, option_b, category) values
('Have you ever been in love with two people at the same time?','More than once','I would never','relationships'),
('Do you check an ex''s social media more frequently than you''d ever admit?','Obviously','Absolutely not','relationships'),
('Have you ever played dumb in a relationship to avoid taking responsibility?','Caught in 4K 😭','Clean conscience','relationships'),
('Do you expect your partner to just know how you''re feeling without you saying it?','Obviously','Absolutely not','relationships'),
('Have you ever ended a relationship over text or without a real conversation?','Guilty 😈','Never 😇','relationships'),
('Do you feel differently about a partner after a major fight than you did before?','Every single time','Who does that?','relationships'),
('Have you ever started dating someone you knew wasn''t right just to fill a gap?','More than once','I would never','relationships'),
('Do you find it hard to say I love you first?','Constantly','Not me','relationships'),
('Have you ever guilt-tripped a partner to get your way?','No comment 👀','Hard no','relationships'),
('Do you have deal-breakers you''ve confidently ignored more than once?','Obviously','Absolutely not','relationships'),
('Have you ever discovered something about an ex that completely changed your view of them?','More than once','Never happened','relationships'),
('Do you put in less effort once you''re comfortable in a relationship?','Caught in 4K 😭','Clean conscience','relationships'),
('Have you ever told someone a secret a partner shared with you in confidence?','Guilty 😈','Never 😇','relationships'),
('Do you fall too fast and then regret it when reality sets in?','Constantly','Not me','relationships'),
('Have you ever pretended to be less bothered by something than you actually were?','More than once','I would never','relationships'),
('Do you start arguments when you feel disconnected rather than just saying so?','Obviously','Absolutely not','relationships'),
('Have you ever stayed in something clearly toxic while making excuses for it?','No comment 👀','Hard no','relationships'),
('Do you find yourself drawn to people who are emotionally unavailable?','Every single time','Who does that?','relationships'),
('Have you ever deleted messages to hide something that was technically innocent?','More than once','I would never','relationships'),
('Do you use humor to deflect serious emotional conversations?','Constantly','Not me','relationships'),
('Have you ever given someone a second chance you privately knew they didn''t deserve?','Yes and I''d do it again','Never happened','relationships'),
('Do you feel responsible for managing your partner''s emotional state?','Obviously','Absolutely not','relationships'),
('Have you ever felt jealous of a partner''s friendship with a specific person?','Caught in 4K 😭','Clean conscience','relationships'),
('Do you keep a running mental tally of effort — yours vs. theirs?','Every single day','Never','relationships'),
('Have you ever used needing space as a way to avoid resolving something?','Guilty 😈','Never 😇','relationships'),
('Do you quietly worry your partner could do better than you?','Constantly','Not me','relationships'),
('Have you ever flirted with someone else while in a relationship?','No comment 👀','Hard no','relationships'),
('Do you find it genuinely hard to trust someone even when they''ve done nothing wrong?','Every relationship','Never','relationships'),
('Have you ever cried about a relationship in a place no one could see you?','More than once','Never happened','relationships'),
('Do you put on a united front in public when things between you and a partner are not okay?','Obviously','Absolutely not','relationships');

insert into questions (text, option_a, option_b, category) values
('Do you have friends you keep around primarily for social status or usefulness?','Guilty 😈','Never 😇','social'),
('Have you ever talked badly about someone the moment they left the room?','Obviously','Absolutely not','social'),
('Do you feel immediate relief the moment you cancel plans?','Every single time','Who does that?','social'),
('Have you ever pretended to be busy to avoid someone you see regularly?','More than once','I would never','social'),
('Do you judge people based on their social media profiles?','Constantly','Not me','social'),
('Have you ever laughed when someone tripped or had an embarrassing moment?','Caught in 4K 😭','Clean conscience','social'),
('Do you put on a louder, more animated version of yourself in group settings?','Constantly','Not me','social'),
('Have you ever deliberately excluded someone from a plan or group chat?','No comment 👀','Hard no','social'),
('Do you pretend to remember people''s names when you have absolutely no idea?','Obviously','Absolutely not','social'),
('Have you ever acted significantly friendlier with someone in public than you actually feel about them?','More than once','I would never','social'),
('Do you leave voice notes unlistened to for days because they feel like a commitment?','Yes and I''d do it again','Never happened','social'),
('Have you ever stayed at a social event past your limit just to avoid seeming rude?','Every single time','Who does that?','social'),
('Do you lose interest in friendships once they stop being fun or convenient?','Guilty 😈','Never 😇','social'),
('Have you ever been genuinely two-faced — warm to someone''s face, brutal behind their back?','No comment 👀','Hard no','social'),
('Do you scroll your phone when someone is actively talking to you?','Constantly','Not me','social'),
('Have you ever chosen not to stand up for someone to avoid being involved?','More than once','I would never','social'),
('Do you keep some friendships going purely out of obligation?','Obviously','Absolutely not','social'),
('Have you ever presented someone else''s idea as your own in a group?','Caught in 4K 😭','Clean conscience','social'),
('Do you silently compete with friends over lifestyle, looks, or success?','Constantly','Not me','social'),
('Have you ever ended a friendship with zero explanation?','Guilty 😈','Never 😇','social'),
('Do you have a friend you secretly think is a bad influence on your life?','Obviously','Absolutely not','social'),
('Have you ever made up an excuse not to lend someone money?','More than once','I would never','social'),
('Do you feel quietly relieved when plans get cancelled at the last minute?','Every single time','Who does that?','social'),
('Have you ever taken a photo of someone without them knowing?','No comment 👀','Hard no','social'),
('Do you avoid answering calls even from people you actually like?','Constantly','Not me','social'),
('Have you ever spread gossip you knew wasn''t fully accurate?','Yes and I''d do it again','Never happened','social'),
('Do you compare your social life to others'' and feel worse for doing it?','Obviously','Absolutely not','social'),
('Have you ever pretended not to use social media to seem more interesting?','Caught in 4K 😭','Clean conscience','social'),
('Do you curate your online presence to appear more exciting than you actually feel?','Every post','Not me','social'),
('Have you ever blocked someone just to see if they''d notice?','Guilty 😈','Never 😇','social');

insert into questions (text, option_a, option_b, category) values
('Do you feel anxious walking into a room full of people you don''t know?','Constantly','Not me','social'),
('Have you ever formed an instant negative judgment about someone based purely on appearance?','More than once','I would never','social'),
('Do you agree with groups even when you privately disagree?','Obviously','Absolutely not','social'),
('Have you ever used someone''s personal struggle as gossip?','No comment 👀','Hard no','social'),
('Do you feel like an outsider even at social events you yourself organised?','Every single time','Who does that?','social'),
('Have you ever made a joke at someone else''s expense to get a laugh?','More than once','I would never','social'),
('Do you find group activities secretly more draining than enjoyable?','Constantly','Not me','social'),
('Have you ever pretended to have forgotten a commitment just to get out of it?','Yes and I''d do it again','Never happened','social'),
('Do you feel more comfortable one-on-one than in a group?','Obviously','Absolutely not','social'),
('Have you ever felt a quiet flicker of pleasure when someone who annoyed you had a setback?','Caught in 4K 😭','Clean conscience','social'),
('Do you present a noticeably different version of yourself to different friend groups?','Constantly','Not me','social'),
('Have you ever deliberately not invited someone to something just to see their reaction?','Guilty 😈','Never 😇','social'),
('Do you feel genuine envy at other people''s social highlights online?','Obviously','Absolutely not','social'),
('Have you ever bonded with someone by mutually talking about a third person?','More than once','I would never','social'),
('Do you check who viewed your posts the second you put them up?','Every single time','Who does that?','social'),
('Have you ever felt completely lonely in a room full of people you know?','No comment 👀','Not me','social'),
('Do you overshare online and immediately regret it?','Constantly','Never happened','social'),
('Have you ever drifted from an entire friend group without any explanation?','More than once','I would never','social'),
('Do you find it easier to be yourself with strangers than with people who know you?','Obviously','Absolutely not','social'),
('Have you ever posted something specifically to make an ex jealous?','Caught in 4K 😭','Clean conscience','social'),
('Do you rehearse even simple conversations in your head before they happen?','Constantly','Not me','social'),
('Have you ever avoided a social event because you weren''t happy with how you looked?','Guilty 😈','Never 😇','social'),
('Do you get irrationally annoyed when someone takes too long to reply?','Obviously','Absolutely not','social'),
('Have you ever felt competitive over who gets more attention in a group?','More than once','I would never','social'),
('Do you use self-deprecating humor to preempt what you think others are already thinking?','Every time','Not me','social'),
('Have you ever sent a message and felt immediate regret the second it was delivered?','Yes and I''d do it again','Never happened','social'),
('Do you privately want fewer friends but much better ones?','Obviously','Absolutely not','social'),
('Have you ever laughed at something genuinely cruel and then felt ashamed?','Caught in 4K 😭','Clean conscience','social'),
('Do you seek validation from strangers online more than from people who actually know you?','Constantly','Not me','social'),
('Have you ever kept a friendship alive purely because ending it felt too complicated?','More than once','I would never','social');

insert into questions (text, option_a, option_b, category) values
('Do you need a specific side of the bed and feel genuinely off sleeping anywhere else?','Obviously','Absolutely not','sleep'),
('Have you ever slept fully clothed because you were too exhausted to change?','More than once','I would never','sleep'),
('Do you immediately check your phone if you wake up at 3am?','Every single time','Who does that?','sleep'),
('Have you ever slept with a light on because of something you watched before bed?','Guilty 😈','Never 😇','sleep'),
('Do you have a bedtime ritual that would look strange to most people?','Constantly','Not me','sleep'),
('Have you ever cried from sheer exhaustion with no other particular reason?','More than once','I would never','sleep'),
('Do you sleep with a fan on even in cold weather?','Obviously','Absolutely not','sleep'),
('Have you ever been told you talk, walk, or do things in your sleep?','Caught in 4K 😭','Clean conscience','sleep'),
('Do you spiral into existential dread the moment your head hits the pillow?','Every single night','Who does that?','sleep'),
('Have you ever fallen asleep somewhere you absolutely should not have?','No comment 👀','Hard no','sleep'),
('Do you nap for just 20 minutes and wake up 3 hours later?','Every single time','Who does that?','sleep'),
('Have you ever spent most of a day in bed just because you could?','More than once','I would never','sleep'),
('Do you have a comfort object — blanket, pillow, or stuffed animal — that has to be there?','Obviously','Absolutely not','sleep'),
('Have you ever been so sleep-deprived you couldn''t recall large parts of your day?','Constantly','Not me','sleep'),
('Do you struggle to fall asleep in complete silence?','Every single night','Silence is fine','sleep'),
('Have you ever set 10 or more alarms and still been late?','Yes and I''d do it again','Never happened','sleep'),
('Do you sleep in the exact same position every single night?','Obviously','Absolutely not','sleep'),
('Have you ever cancelled plans specifically because you needed to sleep?','Guilty 😈','Never 😇','sleep'),
('Do you regularly fall asleep on the sofa and refuse to move to the actual bed?','Constantly','Not me','sleep'),
('Have you ever woken up genuinely unsure what day or time it was?','More than once','I would never','sleep'),
('Do you sleep better with something heavy on top of you?','Obviously','Absolutely not','sleep'),
('Have you ever had a dream so vivid you weren''t sure it was real all morning?','Caught in 4K 😭','I always know','sleep'),
('Do you tell people about your dreams when they didn''t ask?','Every time','I keep them to myself','sleep'),
('Have you ever avoided going to sleep because you didn''t want a good day to end?','More than once','I would never','sleep'),
('Have you ever eaten or drunk something at 2am and barely remembered it the next morning?','No comment 👀','Hard no','sleep'),
('Have you ever read the same sentence 15 times because you were too tired to absorb it?','Every single time','Who does that?','sleep'),
('Do you feel genuine dread if you think you won''t get enough sleep tonight?','Obviously','Absolutely not','sleep'),
('Have you ever been mid-conversation and realized you had no memory of the last few minutes?','Constantly','Not me','sleep'),
('Do you look forward to getting into bed more than almost anything else in your day?','It''s the highlight','Not really','sleep'),
('Have you ever pulled an all-nighter and felt oddly proud of yourself afterward?','Yes and I''d do it again','Never happened','sleep');

insert into questions (text, option_a, option_b, category) values
('Do you have recurring nightmares you''ve never told anyone about?','Guilty 😈','Never 😇','sleep'),
('Do you use sleep as a way to escape things you don''t want to face?','More than once','I would never','sleep'),
('Have you ever completely lost a mid-sentence thought because you were so tired?','Obviously','Absolutely not','sleep'),
('Do you get genuinely angry when woken up unexpectedly?','Caught in 4K 😭','Clean conscience','sleep'),
('Have you ever refused to nap to protect your night sleep and then fallen asleep anyway?','Every single time','Who does that?','sleep'),
('Do you scroll for hours at night telling yourself five more minutes on repeat?','Constantly','Not me','sleep'),
('Have you ever slept more than 12 hours and still felt completely exhausted?','More than once','I would never','sleep'),
('Do you need a specific sleep sound, playlist, or podcast to fall asleep?','Obviously','Absolutely not','sleep'),
('Have you ever tried to go back to sleep specifically to see how a dream ended?','Yes and I''d do it again','Never happened','sleep'),
('Do you delay going to bed even when exhausted because you want more time for yourself?','Every single night','Who does that?','sleep'),
('Have you ever slept through every alarm you set with no memory of turning them off?','Caught in 4K 😭','Clean conscience','sleep'),
('Do you feel physically worse when you sleep at a different time than usual?','Constantly','Not me','sleep'),
('Have you ever lied about why you were tired to avoid admitting you were up until 4am?','More than once','I would never','sleep'),
('Do you rearrange your pillow or blanket repeatedly until it feels exactly right?','Obviously','Absolutely not','sleep'),
('Have you ever dreamed about someone and felt weird around them the next day?','Guilty 😈','Never 😇','sleep'),
('Do you feel anxious lying in bed thinking about everything you didn''t do?','Every single night','Who does that?','sleep'),
('Have you ever used a sleep tracker and become obsessively stressed about the data?','No comment 👀','Hard no','sleep'),
('Do you sleep with socks on but always end up kicking them off during the night?','Every single time','Who does that?','sleep'),
('Do you consider sleeping one of your top three hobbies?','Obviously','Absolutely not','sleep'),
('Have you ever felt genuinely jealous of someone who falls asleep the second they lie down?','Constantly','Not me','sleep'),
('Do you need to check that doors and windows are locked before you can relax enough to sleep?','More than once','I''m very relaxed','sleep'),
('Have you ever woken up and not known where you were for a few seconds?','Yes and I''d do it again','Never happened','sleep'),
('Do you have recurring dreams you have never told anyone about?','Obviously','Absolutely not','sleep'),
('Have you ever felt more rested after 5 hours than after 9?','More than once','I would never','sleep'),
('Do you immediately want to go back to sleep on weekends even after 8 full hours?','Every weekend','Not me','sleep'),
('Have you ever been in a meeting and felt your eyes physically close against your will?','Caught in 4K 😭','Clean conscience','sleep'),
('Do you feel guilty about how much you sleep?','Every morning','Never','sleep'),
('Have you ever fallen down a rabbit hole googling the meaning of a dream?','Obviously','Absolutely not','sleep'),
('Do you experience the falling sensation when nearly asleep and jolt yourself awake?','Every single night','Who does that?','sleep'),
('Have you ever woken up from a nap genuinely convinced it was the next morning?','More than once','I would never','sleep');

insert into questions (text, option_a, option_b, category) values
('Have you ever hidden a purchase from a partner or family member?','No comment 👀','Hard no','money'),
('Do you lie about how much you earn when someone asks?','More than once','I would never','money'),
('Have you ever felt genuine jealousy toward someone who has significantly more money?','Obviously','Absolutely not','money'),
('Do you have debt that nobody close to you knows about?','Guilty 😈','Never 😇','money'),
('Have you ever bought something on credit knowing you couldn''t afford it?','More than once','I would never','money'),
('Do you feel stressed every single time you check your bank balance?','Every single time','Who does that?','money'),
('Have you ever borrowed money and made excuses to avoid paying it back?','No comment 👀','Hard no','money'),
('Do you judge people who have significantly more money than you?','Constantly','Not me','money'),
('Have you ever dated someone at least partly because of their financial stability?','Caught in 4K 😭','Clean conscience','money'),
('Do you have a savings or financial arrangement that nobody close to you knows about?','More than once','I would never','money'),
('Have you ever told someone a lower price than what you actually paid to seem responsible?','Obviously','Absolutely not','money'),
('Do you feel differently about people once you know how much they earn?','Guilty 😈','Never 😇','money'),
('Have you ever pretended you couldn''t afford something to avoid spending the money?','More than once','I would never','money'),
('Do you feel genuinely embarrassed about your current financial situation?','Constantly','Not me','money'),
('Have you ever misrepresented your income on a form or application?','No comment 👀','Hard no','money'),
('Do you feel quiet resentment toward people who never seem to worry about money?','Obviously','Absolutely not','money'),
('Have you ever spent money on something frivolous specifically because you were sad?','Yes and I''d do it again','Never happened','money'),
('Do you have a subscription you''ve been meaning to cancel for more than 6 months?','Every streaming service','I manage mine properly','money'),
('Have you ever bought a gift and decided to keep it for yourself?','Guilty 😈','Never 😇','money'),
('Do you calculate whether a social event is financially worth attending before you commit?','Every single time','Who does that?','money'),
('Have you ever ordered the cheaper option and lied to friends about what you got?','More than once','I would never','money'),
('Do you feel guilt every time you spend money on yourself?','Obviously','Absolutely not','money'),
('Have you ever felt quietly relieved an event was cancelled because it saved you money?','Caught in 4K 😭','Clean conscience','money'),
('Do you present yourself as more financially stable than you actually are?','Constantly','Not me','money'),
('Have you ever lost money through something you''re too embarrassed to admit to anyone?','No comment 👀','Hard no','money'),
('Do you form a more complete opinion of someone once you know their income?','More than once','I would never','money'),
('Have you ever found money and kept it without attempting to find the owner?','Obviously','Absolutely not','money'),
('Do you feel anxious about retirement or future financial security on a regular basis?','Every single day','Who does that?','money'),
('Have you ever bent the truth to get a loan or line of credit approved?','Guilty 😈','Never 😇','money'),
('Do you compare your financial position to your peers and feel behind?','Constantly','Not me','money');

insert into questions (text, option_a, option_b, category) values
('Have you ever spent money that was specifically set aside for something else?','More than once','I would never','money'),
('Do you find it harder to spend money on experiences than on physical things?','Obviously','Absolutely not','money'),
('Have you ever quietly written off money someone owes you rather than ask for it back?','Caught in 4K 😭','Clean conscience','money'),
('Do you secretly judge people for what they spend their money on?','Constantly','Not me','money'),
('Have you ever regretted a major financial decision for years afterward?','More than once','I would never','money'),
('Do you feel a specific kind of shame when your card gets declined?','Obviously','Absolutely not','money'),
('Do you avoid opening bank statements or checking your balance for weeks at a time?','No comment 👀','Hard no','money'),
('Do you feel actual dread as you approach the end of the month?','Every single month','Who does that?','money'),
('Have you ever accepted free food or drinks you didn''t want just because they were free?','Guilty 😈','Never 😇','money'),
('Have you ever made your job title sound more senior to seem financially successful?','More than once','I would never','money'),
('Do you have money habits a financial advisor would genuinely be worried about?','Obviously','Absolutely not','money'),
('Have you ever spent your entire paycheck before the month was even over?','Yes and I''d do it again','Never happened','money'),
('Do you consider most social outings an unnecessary expense?','Constantly','Not me','money'),
('Have you ever taken out one loan to pay off another?','No comment 👀','Hard no','money'),
('Do you feel resentful when you pay for things that others seem to get for free?','Obviously','Absolutely not','money'),
('Have you ever borrowed money with no real plan to pay it back?','Caught in 4K 😭','Clean conscience','money'),
('Do you feel uncomfortable asking for money back from people you know?','Every single time','Who does that?','money'),
('Have you ever sacrificed food, heating, or your own wellbeing just to save money?','More than once','I would never','money'),
('Do you lie to yourself that your finances are fine when they clearly aren''t?','Guilty 😈','Never 😇','money'),
('Have you ever felt judged at a restaurant or store based on what you could afford?','More than once','I would never','money'),
('Do you obsessively compare prices before committing to any purchase?','Obviously','Absolutely not','money'),
('Have you ever seriously considered doing something you weren''t proud of for financial gain?','No comment 👀','Hard no','money'),
('Do you feel your relationship with money is fundamentally unhealthy?','Constantly','Not me','money'),
('Have you ever hidden packaging after buying something to avoid questions about it?','More than once','I would never','money'),
('Do you feel a real difference in confidence based on how much is in your bank account?','Obviously','Absolutely not','money'),
('Have you ever talked yourself out of something you actually needed because of spending guilt?','Caught in 4K 😭','Clean conscience','money'),
('Do you panic when a large unexpected expense comes up?','Every single time','Who does that?','money'),
('Have you ever chosen where to live based on how it would look rather than what you could afford?','More than once','I would never','money'),
('Do you feel your sense of self-worth fluctuate with your financial situation?','Guilty 😈','Never 😇','money'),
('Have you ever lied about having already paid for something to avoid splitting the cost?','No comment 👀','Hard no','money');

insert into questions (text, option_a, option_b, category) values
('Have you ever cheated on someone and never told them?','No comment 👀','Hard no','spicy'),
('Have you ever stayed in a relationship while having feelings for someone else?','More than once','I would never','spicy'),
('Do you ever think about someone other than your partner during intimate moments?','No comment 👀','Hard no','spicy'),
('Have you ever been with someone you knew was in a relationship?','Guilty 😈','Never 😇','spicy'),
('Have you ever used intimacy as a tool to get something you wanted?','More than once','I would never','spicy'),
('Have you ever told someone you loved them mainly to keep them around?','No comment 👀','Hard no','spicy'),
('Have you ever had feelings for a close friend''s partner?','Caught in 4K 😭','Clean conscience','spicy'),
('Do you find people more attractive specifically when they''re off-limits?','Obviously','Absolutely not','spicy'),
('Have you ever faked an emotional connection to get what you wanted?','More than once','I would never','spicy'),
('Do you reach out to exes when you''re lonely, not because you actually care?','Guilty 😈','Never 😇','spicy'),
('Have you ever been with someone for their money or security more than actual love?','No comment 👀','Hard no','spicy'),
('Do you have a situationship you downplay as less significant than it actually is?','More than once','I would never','spicy'),
('Have you ever ended things the moment someone started wanting more from you?','Obviously','Absolutely not','spicy'),
('Do you find it significantly easier to be physically close than emotionally vulnerable?','Constantly','Not me','spicy'),
('Have you ever kept someone on the hook with no intention of actually committing?','No comment 👀','Hard no','spicy'),
('Have you ever kissed someone at an event and both silently agreed it never happened?','Caught in 4K 😭','Clean conscience','spicy'),
('Do you keep secrets from a partner that you freely share with a specific friend instead?','More than once','I would never','spicy'),
('Have you ever used your attractiveness to get ahead in a situation?','Obviously','Absolutely not','spicy'),
('Do you think attraction to someone outside your relationship is completely normal?','Obviously','Absolutely not','spicy'),
('Have you ever had a close friendship that both of you knew was really something else?','No comment 👀','Hard no','spicy'),
('Do you send slightly ambiguous messages to someone and enjoy the resulting tension?','Constantly','Not me','spicy'),
('Have you ever let someone believe you were more interested than you actually were?','More than once','I would never','spicy'),
('Do you have a number you''ve never told anyone the full honest truth about?','No comment 👀','Hard no','spicy'),
('Have you ever been with someone specifically to get over someone else?','Guilty 😈','Never 😇','spicy'),
('Do you find yourself physically drawn to people who treat you badly?','Caught in 4K 😭','Clean conscience','spicy');

insert into questions (text, option_a, option_b, category) values
('Have you ever received attention from someone you shouldn''t have, and not stopped it?','No comment 👀','Hard no','spicy'),
('Do you think about what your life would look like with a specific other person?','More than once','I would never','spicy'),
('Have you ever been the other person in a situation and justified it completely to yourself?','No comment 👀','Hard no','spicy'),
('Do you monitor someone''s social media that you claim you no longer care about?','Obviously','Absolutely not','spicy'),
('Have you ever initiated something physical and then let them believe it was their idea?','Caught in 4K 😭','Clean conscience','spicy'),
('Do you go quiet and unreachable when someone gets emotionally too close?','Constantly','Not me','spicy'),
('Have you ever pursued someone knowing they were in a vulnerable moment?','No comment 👀','Hard no','spicy'),
('Do you maintain an emotional connection with someone your partner doesn''t know about?','More than once','I would never','spicy'),
('Have you ever ended a serious relationship because you were bored rather than unhappy?','Obviously','Absolutely not','spicy'),
('Do you stay in contact with exes in ways your current partner would be uncomfortable knowing?','No comment 👀','Hard no','spicy'),
('Have you ever crossed a physical line with someone and convinced yourself it didn''t count?','Caught in 4K 😭','Clean conscience','spicy'),
('Do you think you have been the genuinely toxic one in at least one relationship?','Guilty 😈','Never 😇','spicy'),
('Have you ever told strategic half-truths in a relationship to avoid a real conversation?','More than once','I would never','spicy'),
('Do you feel more alive in relationships that have an element of chaos or uncertainty?','Obviously','Absolutely not','spicy'),
('Have you ever made a decision you deeply regret because you were too attracted to someone?','No comment 👀','Hard no','spicy'),
('Do you enjoy being wanted more than you actually enjoy the relationship itself?','Constantly','Not me','spicy'),
('Have you ever been in a room with someone in a relationship and both of you knew what was happening?','No comment 👀','Hard no','spicy'),
('Do you tell yourself you''re not ready for commitment when really you just haven''t met the right chaos?','Caught in 4K 😭','Clean conscience','spicy'),
('Have you ever fallen for someone based entirely on how they made you feel, not who they actually were?','More than once','I would never','spicy'),
('Do you think you''ve genuinely broken someone''s heart without fully realizing it at the time?','Guilty 😈','Never 😇','spicy'),
('Have you ever faked more enthusiasm than you felt in an intimate situation?','No comment 👀','Hard no','spicy'),
('Do you find yourself more interested in someone after they stop chasing you?','Obviously','Absolutely not','spicy'),
('Have you ever stayed in something physical longer than you should have because it was convenient?','More than once','I would never','spicy'),
('Have you ever told someone what they wanted to hear, fully knowing it wasn''t true?','Caught in 4K 😭','Clean conscience','spicy'),
('Do you think complete honesty in a relationship is actually impossible?','Obviously','Absolutely not','spicy');
